sudo: required

language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - cat docker/requirements_system.txt | sudo xargs apt-get install -y

install:
  - pip install -r docker/requirements_python.txt
  - make install

script: "cd Tests && make testpython"
